### PR TITLE
Adding task enforcing use of Systemd script for CentOS>6

### PR DESCRIPTION
**Pull request by jgagnon1**
Adding task enforcing use of Systemd script for CentOS>6

### CODE REVIEW

**Comment by wtanaka** [comment]
@jgagnon1 thanks!

It seems as though this is running into an error, at least within the centos:7 docker test?

```
NOTIFIED: [ansible-role-apache-kafka | restart kafka] ************************* 
[0;31mfailed: [centos-7] => {"changed": true, "cmd": "/etc/init.d/kafka.sh stop && /etc/init.d/kafka.sh start ", "delta": "0:00:00.002848", "end": "2017-12-21 21:21:31.047291", "item": "", "rc": 127, "start": "2017-12-21 21:21:31.044443"}[0m
[0;31mstderr: /bin/sh: /etc/init.d/kafka.sh: No such file or directory[0m
[0;31m
FATAL: all hosts have already failed -- aborting[0m
```

**Comment by jgagnon1** [comment]
Will check this out; do you have documentation how to run tests ?

**Comment by wtanaka** [comment]
@jgagnon1 sorry for the delay in replying, the tests are run with:

https://github.com/wtanaka/ansible-role-apache-kafka/blob/f2264ddd425d9d3b96e81b961d594a366d49f1e1/.travis.yml#L11-L15

and

https://github.com/wtanaka/ansible-role-apache-kafka/blob/f2264ddd425d9d3b96e81b961d594a366d49f1e1/circle.yml#L14-L18

**Comment by jgagnon1** [comment]
@wtanaka Updated restart handlers and tests are passing now.

**Comment by wtanaka** [comment]
@jgagnon1 thanks!

**Pull request merged**
